feat(report): 添加自动错误报告功能 - 测试

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -76,6 +76,11 @@ inputs:
     description: 指定更新网站地图的方式 (直接提交或拉取请求)
     default: 拉取请求
 
+  auto_bug_report:
+    description: 指定当发生错误时是否自动向我们提交错误报告 (这会包含您的工作流链接和相关参数信息，不会包含您的个人信息)
+    required: false
+    default: 启用
+
 runs:
   using: composite
   steps:
@@ -122,6 +127,9 @@ runs:
         LOCATION: ${{ inputs.location }}
         UPDATE: ${{ inputs.update }}
       run: |
+        # 测试，模拟出错 - test202501142122
+        exit 114514
+
         # 后面都要用的
         # 获取当前日期和时间
         DATE_TIME=$(date '+%Y/%m/%d %H:%M')
@@ -248,3 +256,56 @@ runs:
             echo "[DEBUG] 没有有效自动合并方式，跳过启用自动合并"
           fi
         fi
+
+    - name: 提交错误议题(如果出错)
+      shell: bash
+      continue-on-error: true # 不要因为提交错误议题的错误影响整个工作流
+      env:
+        DEBUG: ${{ inputs.debug }}
+        AUTO_BUG_REPORT: ${{ inputs.auto_bug_report }}
+        FAILURE_STEP: ${{ env.FAILURE_STEP }}
+        GH_TOKEN: ${{ github.token }} # 不要使用使用者账户创建议题
+        # --- 错误反馈收集参数 ---
+        LOCATION: ${{ inputs.location }}
+        BASIC_LINK: ${{ inputs.basic_link }}
+        FILE_TYPE: ${{ inputs.file_type }}
+        IGNORE_FILE: ${{ inputs.ignore_file }}
+        WEBSITE_PATH: ${{ inputs.website_path }}
+        LABELS: ${{ inputs.labels }}
+        AUTO_MERGE: ${{ inputs.auto_merge }}
+        UPDATE: ${{ inputs.update }}
+      if: env.FAILURE_STEP # 只有在步骤失败时执行
+      run: |
+        echo "[INFO] 此工作流似乎在某些地方出现了错误，正在检查是否启用了自动错误报告..."
+        CLEAN_AUTO_BUG_REPORT=$(echo "$AUTO_BUG_REPORT" | tr '[:upper:]' '[:lower:]' | sed "s/[\"\'\`-]//g")
+        if [[ "$DEBUG" ]]; then
+          echo "[DEBUG] 清理后传入的自动错误报告开关: $CLEAN_AUTO_BUG_REPORT"
+        fi
+        case "$CLEAN_AUTO_BUG_REPORT" in
+          "true" | "启用" | "开启" | "open")
+            echo "[INFO] 自动错误报告已启用"
+            if [[ "$DEBUG" ]]; then
+            echo "[DEBUG] 获取到的出错步骤: $FAILURE_STEP"
+            fi
+            case "$FAILURE_STEP" in
+            "权限" | "权限错误" | "没有权限" | "缺少权限")
+              echo "[WARNING] 很抱歉，有关权限的错误我们无法处理，请参阅我们的文档了解你可能需要赋予GitHub Action哪些权限"
+              echo "[WARNING] https://github.com/DuckDuckStudio/Sitemap_Creator/blob/main/README.md#1-%E5%A6%82%E4%BD%95%E5%85%81%E8%AE%B8-github-action-%E5%88%9B%E5%BB%BA%E6%8B%89%E5%8F%96%E8%AF%B7%E6%B1%82--%E6%8E%A8%E9%80%81%E4%BF%AE%E6%94%B9"
+              ;;
+            "参数错误")
+              echo "[WARNING] 很抱歉，参数错误需要您自己解决，建议您查看日志中显示 '# 后面都要用的' 的这步的输出，看看是否有参数错误信息。"
+              echo "[WARNING] 如果您认为您的参数是正确无误的，请使用 'debug: true' 来启用调试输出，看看调试输出的信息是否准确。"
+              echo "[WARNING] 如果您还是认为这是 Sitemap Creator 的问题，请向我们提交 Issue。"
+            *)
+              echo "[WARNING] 记录的错误步骤没有匹配任何分类"
+              # 生成工作流 URL
+              WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+              gh issue create --repo "DuckDuckStudio/Sitemap_Creator" --title "[错误报告(未匹配)] 在运行工作流时出现未匹配的错误" --body "> 这是一个由 [Sitemap Creator](https://github.com/DuckDuckStudio/Sitemap_Creator) 自动创建的错误报告。\n### 问题类别\n\n未匹配到任何错误分类:\n\`\`\`txt\n$FAILURE_STEP\n\`\`\`\n\n### 错误工作流链接\n\n$WORKFLOW_URL\n\n### 使用的参数\n\n\`\`\`yml\ndebug: $DEBUG\nauto_bug_report: $AUTO_BUG_REPORT\nlocation: $LOCATION\nbasic_link: $BASIC_LINK\nfile_type: $FILE_TYPE\nignore_file: $IGNORE_FILE\nwebsite_path: $WEBSITE_PATH\nlabels: $LABELS\nauto_merge: $AUTO_MERGE\nupdate: $UPDATE\n\`\`\`\n\n"
+              echo "[INFO] 已提交错误报告"
+              ;;
+            esac
+            ;;
+          *)
+            echo "[INFO] 自动错误报告已禁用"
+            ;;
+        esac
